version: "3"

services:
  database:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_DB: "mydb"
      POSTGRES_USER: "aleksei"
      POSTGRES_PASSWORD: "pass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - asyncio-book-db-data:/var/lib/postgresql/data/pgdata
      # - ./create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    ports:
      - "5432:5432"

volumes:
  asyncio-book-db-data:

